version: '3'

services:
  web:
    image: nginx:alpine
    container_name: http-server
    ports:
      - "${HOST_IP:-0.0.0.0}:${HOST_PORT:-8080}:80"
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
